services:
  jaeger:
    image: jaegertracing/all-in-one:1.32
    environment:
      - OLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
