receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/aspecto:
    endpoint: otelcol.aspecto.io:4317
    headers:
      Authorization: ${ASPECTO_API_KEY}

  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  zpages:
    endpoint: :55679

service:
  telemetry:
    logs:
      level: 'debug'
  extensions: [zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger, otlp/aspecto]
