services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    environment:
      - ASPECTO_TOKEN=${ASPECTO_TOKEN}
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension


  aws-otelcol:
    image: public.ecr.aws/aws-observability/aws-otel-collector:v0.26.0
    environment:
      - ASPECTO_TOKEN=${ASPECTO_TOKEN}
      - AWS_REGION=us-west-2
    command: ["--config=/etc/otel-agent-config.yaml"]
    volumes:
      - ./aws-otelcol-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
